#! /bin/bash
#
# Copyright (c) 2009, 2011, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#
# Copy the Hadoop files
#

# Resolve location of this script
    me="${BASH_SOURCE[0]}"
    while [ -h "$me" ]; do
        me=`readlink -e "$me"`
    done

me_dir=`dirname $me`
. $me_dir/ext2setup

. $me_dir/ext2cp_setup

hadoop=$dir
ext2hd=/

java -classpath $cp $h $mc copyin -r -disk $dfile -from $hadoop/lib -ext2path $ext2hd
java -classpath $cp $h $mc copyin -r -disk $dfile -from $hadoop/conf -ext2path $ext2hd
java -classpath $cp $h $mc copyin -r -disk $dfile -from $hadoop/cmd_jars -ext2path $ext2hd

# basic support jar files
jars=`ls -1 $hadoop/*.jar`
for j in $jars; do
  java -classpath $cp $h $mc copyin -disk $dfile -from $j -ext2path $ext2hd
done

