#! /bin/bash
#
# Copyright (c) 2009, 2011, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
#
# Initializes the disk file, deleting it first if it already exists

# Resolve location of this script
    me="${BASH_SOURCE[0]}"
    while [ -h "$me" ]; do
        me=`readlink -e "$me"`
    done

size=256m

me_dir=`dirname $me`
. $me_dir/ext2setup

rm -f $dfile

while [ "$1" != "" ];
do
  case $1 in
    -size )
      shift
      size=$1
      ;;
    * )
      break
      ;;
  esac
  shift
done

mkdir -p `dirname $dfile`
mkfile=`which mkfile 2>/dev/null`
if [ "$mkfile" = "" ] ;
then
  echo "no mkfile command found on path"
  exit 1;
fi
mkfile $size $dfile
java -classpath $cp $h $mc format -disk $dfile
