#! /bin/bash
#
# Copyright (c) 2009, 2011, Oracle and/or its affiliates. All rights reserved.
# DO NOT ALTER OR REMOVE COPYRIGHT NOTICES OR THIS FILE HEADER.
#
# This code is free software; you can redistribute it and/or modify it
# under the terms of the GNU General Public License version 2 only, as
# published by the Free Software Foundation.
#
# This code is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
# version 2 for more details (a copy is included in the LICENSE file that
# accompanied this code).
#
# You should have received a copy of the GNU General Public License version
# 2 along with this work; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA.
#
# Please contact Oracle, 500 Oracle Parkway, Redwood Shores, CA 94065 USA
# or visit www.oracle.com if you need additional information or have any
# questions.
# 
# variant of run with a configurable disk in addition to java and scratch and sibling guest
#
mount="/user"
debug=""
echo=""
vmargs=""

while [ "$1" != "" ] ;
do
  case "$1" in
    "-d" )
      debug="-d"
      ;;
    -J* )
    if [ "$vmargs" = "" ] ;
    then
      vmargs=$1
    else
      vmargs="$vmargs $1"
    fi
    ;;
    "-mount")
      shift
      mount=$1
      ;;
    "-echo" )
      echo="-echo"
      ;;
    *)
      break
      ;;
  esac
  shift
done

com.oracle.max.ve.shell/run $echo $vmargs $debug -fstable "ext2:/blk/0:/maxve/java:ro;ext2:/blk/1:${mount};ext2:/blk/2:/scratch;sg:/exports:/sg" $*
